let ctx = null
const getCtx = () => { if (!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)(); return ctx }
const play = fn => { try { fn(getCtx()) } catch {} }

export const sounds = {
  kill: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sawtooth'; o.frequency.setValueAtTime(220, c.currentTime); o.frequency.exponentialRampToValueAtTime(55, c.currentTime + 0.4); g.gain.setValueAtTime(0.3, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.5); o.start(); o.stop(c.currentTime + 0.5) }),
  vote: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sine'; o.frequency.value = 600; g.gain.setValueAtTime(0.15, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.1); o.start(); o.stop(c.currentTime + 0.1) }),
  night: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sine'; o.frequency.setValueAtTime(80, c.currentTime); o.frequency.linearRampToValueAtTime(60, c.currentTime + 1.5); g.gain.setValueAtTime(0, c.currentTime); g.gain.linearRampToValueAtTime(0.2, c.currentTime + 0.3); g.gain.linearRampToValueAtTime(0, c.currentTime + 1.5); o.start(); o.stop(c.currentTime + 1.5) }),
  day: () => play(c => { [523, 659, 784].forEach((f, i) => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sine'; o.frequency.value = f; g.gain.setValueAtTime(0, c.currentTime + i * 0.1); g.gain.linearRampToValueAtTime(0.15, c.currentTime + i * 0.1 + 0.05); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + i * 0.1 + 0.4); o.start(c.currentTime + i * 0.1); o.stop(c.currentTime + i * 0.1 + 0.4) }) }),
  win: () => play(c => { [523, 659, 784, 1047].forEach((f, i) => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'triangle'; o.frequency.value = f; g.gain.setValueAtTime(0, c.currentTime + i * 0.12); g.gain.linearRampToValueAtTime(0.2, c.currentTime + i * 0.12 + 0.05); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + i * 0.12 + 0.5); o.start(c.currentTime + i * 0.12); o.stop(c.currentTime + i * 0.12 + 0.5) }) }),
  lose: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sawtooth'; o.frequency.setValueAtTime(300, c.currentTime); o.frequency.exponentialRampToValueAtTime(100, c.currentTime + 0.8); g.gain.setValueAtTime(0.2, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.8); o.start(); o.stop(c.currentTime + 0.8) }),
  tick: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'square'; o.frequency.value = 1000; g.gain.setValueAtTime(0.05, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.05); o.start(); o.stop(c.currentTime + 0.05) }),
  join: () => play(c => { const o = c.createOscillator(), g = c.createGain(); o.connect(g); g.connect(c.destination); o.type = 'sine'; o.frequency.setValueAtTime(800, c.currentTime); o.frequency.linearRampToValueAtTime(1000, c.currentTime + 0.1); g.gain.setValueAtTime(0.1, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.2); o.start(); o.stop(c.currentTime + 0.2) }),
}
